@startuml
left to right direction

class Course {
    +courseId: String
    +title: String
    +strategy: GradingStrategy
    +modules: List<Module>
    +setStrategy(s: GradingStrategy): void
    +getStrategy(): GradingStrategy
}

interface GradingStrategy {
    +calculateFinalGrade(): double
}

class PercentageBased {
    +calculateFinalGrade(): double
}

class GPABased {
    +calculateFinalGrade(): double
}

class Module {
    +moduleId: String
    +name: String
    +lessons: List<Lesson>
}

class Lesson {
    +lessonId: String
    +title: String
    +contentUrl: String
    +getTitle(): String
}

class Student {
    +requestEnrollment(course: Course): EnrollmentRequest
}

class Instructor {
    +reviewRequest(rew: EnrollmentRequest, approve: boolean): void
}

class EnrollmentRequest {
    +requestId: String
    +student: Student
    +course: Course
    +createdAt: String
    +getStudent(): Student
    +getCourse(): Course
}

Course "1" --> "0..*" Module : modules
Course "1" --> "1" GradingStrategy : strategy
GradingStrategy <|.. PercentageBased
GradingStrategy <|.. GPABased
Module "1" --> "0..*" Lesson : lessons
EnrollmentRequest "0..*" --> "1" Student : student
EnrollmentRequest "0..*" --> "1" Course : course
Instructor "1" --> "0..*" EnrollmentRequest : reviews
@enduml